data:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
  entrypoint: /bin/true

postgres:
  image: turistforeningen/sherpa-postgres:latest
  volumes_from:
    - data
  command: postgres -N 300 -d 1
  restart: always

psql:
  build: .
  links:
    - postgres
  command: /bin/true
